### ISSUE TITLE
Panic in shares.Readdir when one of the share localdirs doesn't exist

### ISSUE THREAD

**Issue by sgielen** [Jille/rufs#45]
```
root@jet:~# rufs -http_allow_hosts 192.168.1.0/24 -mountpoint /mnt/rufs -allow_all_users
20:07:27.011210 client.go:43: starting rufs v2.0 (fd19a4d)
20:07:27.059071 contentserver.go:52: content server listening on addr :12010.
20:07:27.060109 web.go:61: web server listening on addr :12011.
20:07:28.811835 connectivity.go:103: Connected to RuFS. My endpoints: [<snip>:12010]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x90dd50]

goroutine 91 [running]:
github.com/sgielen/rufs/client/shares.Readdir(0xc0000a6550, 0xe, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/sjors/Projecten/rufs/client/shares/shares.go:139 +0xb0
github.com/sgielen/rufs/client/content.content.ReadDir(0xfe9980, 0xc0000a9ef0, 0xc0002a1780, 0xa790e0, 0xc000284a00, 0xfe9f68)
	/Users/sjors/Projecten/rufs/client/content/contentserver.go:107 +0xb8
github.com/sgielen/rufs/proto._ContentService_ReadDir_Handler.func1(0xfe9980, 0xc0000a9ef0, 0xa5c4c0, 0xc0002a1780, 0xc0000a6550, 0xe, 0x0, 0x0)
	/Users/sjors/Projecten/rufs/proto/rufs_grpc.pb.go:519 +0x89
github.com/sgielen/rufs/client/content.unaryInterceptor(0xfe9980, 0xc0000a9ef0, 0xa5c4c0, 0xc0002a1780, 0xc00029c920, 0xc00000cdb0, 0xc000284ba0, 0x4a13c6, 0xa89a80, 0xc0000a9ef0)
	/Users/sjors/Projecten/rufs/client/content/contentserver.go:80 +0x11a
github.com/sgielen/rufs/proto._ContentService_ReadDir_Handler(0xa790e0, 0x138ccc8, 0xfe9980, 0xc0000a9ef0, 0xc00024ac00, 0xf502c0, 0xfe9980, 0xc0000a9ef0, 0x0, 0x0)
	/Users/sjors/Projecten/rufs/proto/rufs_grpc.pb.go:521 +0x150
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00014bdc0, 0xfef218, 0xc000082900, 0xc0001cf560, 0xc00020c390, 0x1346e60, 0x0, 0x0, 0x0)
	/Users/sjors/go/pkg/mod/google.golang.org/grpc@v1.37.0/server.go:1217 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc00014bdc0, 0xfef218, 0xc000082900, 0xc0001cf560, 0x0)
	/Users/sjors/go/pkg/mod/google.golang.org/grpc@v1.37.0/server.go:1540 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0000a66b0, 0xc00014bdc0, 0xfef218, 0xc000082900, 0xc0001cf560)
	/Users/sjors/go/pkg/mod/google.golang.org/grpc@v1.37.0/server.go:878 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/Users/sjors/go/pkg/mod/google.golang.org/grpc@v1.37.0/server.go:876 +0x1fd
```

**Comment by Jille** [comment]
I suspect this is the same bug as #30 

```
  if remotePath == "" {
    for remote := range circles[circle].shares { # L 139
```

I don't think it's related to a localdir not existing, but to the circle not being in `circles`. If this is #30, that'd be because initializing new circles at runtime doesn't work.
