### ISSUE TITLE
Panic on Windows in ReadFromUDP (wsarecvfrom) on udpMultiplexer socket

### ISSUE THREAD

**Issue by sgielen** [Jille/rufs#66]
```
panic: read udp4 0.0.0.0:58063: wsarecvfrom: De verbinding is verbroken omdat keep-alive-activiteit een fout heeft ontdekt tijdens de bewerking.

goroutine 10 [running]:
github.com/sgielen/rufs/client/connectivity/udptransport.(*udpMultiplexer).reader(0xc00003d590)
	C:/Users/Sjors/Source/rufs/client/connectivity/udptransport/udpmultiplexer.go:87 +0x34b
created by github.com/sgielen/rufs/client/connectivity/udptransport.newUDPMultiplexer
	C:/Users/Sjors/Source/rufs/client/connectivity/udptransport/udpmultiplexer.go:38 +0x109
```

At this time, 58063 was my UDP listening port. Perhaps some timeout occurred on it?

**Comment by sgielen** [comment]
This seems relevant: https://stackoverflow.com/questions/1016655/socket-error-10052-on-udp-socket (via https://social.msdn.microsoft.com/Forums/en-US/0b14bfda-6209-4511-92f1-061b7bf4f692/udp-server-the-connection-has-been-broken-due-to-keepalive-activity-?forum=csharpgeneral)
