### ISSUE TITLE
Crash when initializing first circle

### ISSUE THREAD

**Issue by Jille** [Jille/rufs#93]
Got this crash while adding the first circle in the webui

```
Jun 05 22:44:40 t-2375 rufs[28706]: panic: runtime error: invalid memory address or nil pointer dereference
Jun 05 22:44:40 t-2375 rufs[28706]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8e60b0]
Jun 05 22:44:40 t-2375 rufs[28706]: goroutine 193 [running]:
Jun 05 22:44:40 t-2375 rufs[28706]: github.com/sgielen/rufs/client/metrics.(*circleMetrics).SetOrAdd(0x0, 0x9, {0xc000267f90, >
Jun 05 22:44:40 t-2375 rufs[28706]:         /home/quis/go/src/github.com/sgielen/rufs/client/metrics/metrics.go:93 +0x50
Jun 05 22:44:40 t-2375 rufs[28706]: github.com/sgielen/rufs/client/metrics.increaseCounter(...)
Jun 05 22:44:40 t-2375 rufs[28706]:         /home/quis/go/src/github.com/sgielen/rufs/client/metrics/metrics.go:40
Jun 05 22:44:40 t-2375 rufs[28706]: github.com/sgielen/rufs/client/metrics.AddVfsReaddirs(...)
Jun 05 22:44:40 t-2375 rufs[28706]:         /home/quis/go/src/github.com/sgielen/rufs/client/metrics/generated.go:43
Jun 05 22:44:40 t-2375 rufs[28706]: github.com/sgielen/rufs/client/vfs.Readdir.func1()
Jun 05 22:44:40 t-2375 rufs[28706]:         /home/quis/go/src/github.com/sgielen/rufs/client/vfs/vfs.go:176 +0x18b
Jun 05 22:44:40 t-2375 rufs[28706]: created by github.com/sgielen/rufs/client/vfs.Readdir
Jun 05 22:44:40 t-2375 rufs[28706]:         /home/quis/go/src/github.com/sgielen/rufs/client/vfs/vfs.go:173 +0x8f
Jun 05 22:44:40 t-2375 systemd[1]: rufs.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
```

**Comment by Jille** [comment]
```
$ ls -l rufs/all/
ls: reading directory 'rufs/all/': Software caused connection abort
total 0
```

triggered the same crash

**Comment by Jille** [comment]
This is caused by the mismatch in the circle name. The certificate presented by the CA contains "rufs.hashru.nl", but the configured circle is "rufs.hashru.nl:12000".

The errors went away when I renamed the circle to "rufs.hashru.nl" locally.

So this is really a duplicate of #86
